### ISSUE TITLE
Mockups

### ISSUE THREAD

**Issue by CoupKwon-dot** [jesus25031/Ciclo-3-UTP#12]

**Comment by vanequina** [comment]
Hola! Este sería el primer borrador de Mock Up del Sprint 1. Esta sin colores o estilos, además del logo pero la idea es pulirlo con las ideas de todos. Lo realice en Adobe XD. 

![Web 1920 – 1](https://user-images.githubusercontent.com/86982710/131924544-82d86877-63a2-40cd-b7c6-ed3dfe979ad3.png)
![Web 1920 – 2](https://user-images.githubusercontent.com/86982710/131924550-d188be24-aaa1-4ef1-a9f7-541e147237eb.png)
![Web 1920 – 3](https://user-images.githubusercontent.com/86982710/131924553-8e70d86e-8586-4105-b312-523094a95aff.png)
![Web 1920 – 4](https://user-images.githubusercontent.com/86982710/131924558-0e4de434-7dfc-4f71-8eea-439912c289a0.png)
![Web 1920 – 5](https://user-images.githubusercontent.com/86982710/131924559-e8105b95-e768-4e25-8311-7e4405fbb6cb.png)

**Comment by cridavifer** [comment]
Esta muy bien @vanequina
